server:
  port: 9000

spring:
  application:
    name: cakecandy-auth-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/cakebd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: myjwtsecret12345
  expiration-ms: 3600000
